#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# For "Python 3.7.3", pushes with tags "3", "3.7", "3.7.3", and commit hash

echo "[***] Post_Push hook running"

# get Python version from image's environmental variables, without running it
export PYTHON_VERSION_X_Y_Z=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{$value}} {{end}}' $IMAGE_NAME | grep -oP 'PYTHON_VERSION=\K\d+(.\d+(.\d+\w*)?)?')
export PYTHON_VERSION_X_Y=$(echo $PYTHON_VERSION_X_Y_Z | cut -f 1-2 -d .)
export PYTHON_VERSION_X=$(echo $PYTHON_VERSION_X_Y_Z | cut -f 1 -d .)
echo "     Versions: $PYTHON_VERSION_X  $PYTHON_VERSION_X_Y  $PYTHON_VERSION_X_Y_Z  $SOURCE_COMMIT"

docker tag $IMAGE_NAME $DOCKER_REPO:$PYTHON_VERSION_X_Y_Z
docker push $DOCKER_REPO:$PYTHON_VERSION_X_Y_Z

docker tag $IMAGE_NAME $DOCKER_REPO:$PYTHON_VERSION_X_Y
docker push $DOCKER_REPO:$PYTHON_VERSION_X_Y

docker tag $IMAGE_NAME $DOCKER_REPO:$PYTHON_VERSION_X
docker push $DOCKER_REPO:$PYTHON_VERSION_X

docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:$SOURCE_COMMIT
